### ISSUE TITLE
Saving tiddlers saves the whole wiki

### ISSUE THREAD

**Issue by virzen** [donmor/TiddloidLite#1]
Hi! Thanks a lot for this project, it's very cool to have my wiki accessible on a smartphone!

I've noticed that saving a tiddler takes unusually long time, compared to web version. I've also noticed that immediately after tiddler is saved I get an alert "Saved wiki". Which takes me to conclusion that each time a tiddler is saved, the whole wiki is saved. And it probably takes some time because, in my case, it's taken directly from Google Drive.

Is there an option to decouple saving tiddlers and saving whole wiki? I'm also using TiddlyDrive, which does exactly that—it saves my wiki periodically instead of on each change.

I've tried to look at the code, but couldn't find the logic behind saving tiddlers. I found the [`saveWiki` method](https://github.com/donmor/TiddloidLite/blob/master/app/src/main/java/top/donmor/tiddloidlite/TWEditorWV.java?ts=4#L273), but I don't get much of it either. I'm not very well-versed in Java, nor Android APIs though.

Have you considered such option before? Is there something that prevented you from doing this @donmor?

**Comment by donmor** [comment]
Hi @virzen ,

I consider Tiddloid and the Lite version a port of TiddlyDesktop, a desktop app to use TiddlyWiki. These apps implements a saver in the TW5, and when a tiddler saved and the saver supports autosaving, TW5 automatically saves the whole file. This function can be disabled by setting [Control Panel]>[Saving]>[General]>[Autosave] to [Do not save changes automatically].
As for the long saving time, it is because that the TW5 would be paused until the whole wiki is written to the target file, and I'm not sure about the possibility that saving the files in separate threads could be unstable.

donmor

**Comment by mikegr** [comment]
First I have to say that I am very happy to have finally a way on Android to access my Tiddlywiki from a network storage.
I would suggest to cache the save requests from the Webview and only sync when returning back to main screen or the webview is destroyed.

**Comment by donmor** [comment]
Ur,  you know Android drops background apps easily, especially on devices with less RAM and highly customized OS(especially in China). I'm not willing to see if the app is terminated without changes saved while searching on Bing.
